<h3>About</h3>

Vznik hry Quadra Speed Boosters má jednoduchý důvod. Nápad udělat on-line hru totiž dostane snad většina webmasterů a lidí, kteří si hrají s programováním a webem. Já ho také dostal, ale spíš náhodou. Snažil jsem se pořád přijít na něco originálního. Většina her v té době byla o dobývání, stavění armád a bojích, čemuž jsem se určitě chtěl vyhnout a odklonit se trochu od mainstreamu. Napadly mě závody a sázení. Nejdříve v návrhu figurovaly dostihy a koně, ale pak jsem přehodil téma na zcela odlišné prostředí. Na tehdy docela aktuální - tuším, že v tu dobu jsem se koukal na třetí díl série Star Wars Episode III - Revenge of the Sith, samozřejmě už po třetí. Koně tehdy musely ustoupit futuristickým závodům kluzáků ze světa Star Wars. K tomuto došlo náhodou někdy <strong class="extra">v lednu roku 2006</strong>. Po důkladném promyšlení pár věcí, jsem se odhodlal něco udělat. A skutečně! O tři měsíce později (<strong class="extra">březen 2006</strong>) byl vymyšlen název Quadra Speed Boosters a obrázek s letícím Anakinem Skywalkerem, který byl posléze umístěn nad nápis "Coming soon" na adrese <strong class="extra">http://qsb.wz.cz/</strong>. Pak jsem na hru zas zapomněl a připomenuto vše bylo až 1.8. 2006, kdy jsem se dostal po půlce prázdnin domů a skutečně začínám dělat něco na neznámém projektu s kódovým označením Quadra Speed Boosters. <strong class="extra">8.8. 2006 vzniká první kód</strong><br />
<br />
<h4>Vývoj I</h4>Počáteční nadšení pro vývoj mě pohánělo a jelikož byly prázdniny, i přes neustálé výlety a odjezdy jsem stihl udělat velký kus práce. Zhruba 40% kódu bylo hotovo. S testováním mi pomáhalo pár přátel <span class="ultra"><em>(Nípal, Hannibal, lacop...)</em></span>, takže vše běželo krásně. Po velmi hutné práci místo odpočinku přichází škola a práce se téměř zastavuje. Původní datum spuštění hry bylo určeno na <strong class="extra">1.10. 2006</strong>. Třetího jsem si uvědomil, že pořád hodně věcí chybí a s každou udělanou 2 nové přibydou. Posunutí na 15.10. 2006 snad ani nemusím zmiňovat, protože ho také nebylo možné dodržet. Pustil jsem se tedy do další práce, ale vývoj se dostal do fáze, kdy člověk skoro ztratí motivaci. Nadšení opadlo už taky a já musel dodělávat takový ty otravný, nudný a samozřejmě nezbytný blbosti. Spuštění bylo odloženo na Q1 2007. Z chyb se člověk učí a já si nechal větší rezervu :)<br />

<br />
<h4>Spuštění</h4>O trochu dříve než jsem čekal, jsem dodělal pár posledních věcí, radši nic netestoval, abych neobjevil další bugy a spustil hru pro betatest na adrese <strong class="extra">www.qsb.ic.cz</strong>. <strong class="extra">9.12. 2006</strong> bylo QSB konečně otevřeno pro veřejnost! Tento datum bych pokládal za jedno z nejdůležitějších, protože se jedná o opravdové spuštění hry. Hned ten den jsem napsal známým a podařilo se nám do večera sehnat přes 30 lidí. Někteří z nich možná hrají QSB do nynějška.<br />
Jak vypadalo ale tehdy QSB z pohledu hráče? bylo vcelku dobré. Kluzák sestával z podvozku, motoru, energodržáků a chladiče. Podvozek byl rozdělen podle typů motorů (a ne na tři typy, jak je tomu nyní). Motor neměl rychlost, ale jen výkon v MW. Neexistovaly stáje <span class="ultra"><em>(tudíž ani pohár)</em></span> ani banky a běžel jenom jeden přepočet denně (ve 23:00). Nešlo zakládat závody <span class="ultra"><em>(o to se staral pouze systém)</em></span> a největší výdělky byly přes výhry a paliva. U závodů šlo vybírat pouze styl, nikoli chování. Brigády také ještě nebyly (přidělány byly zhruba po týdnu), ale věřte tomu nebo ne, hratelné to bylo také dost. Jen to časem omrzelo.<br />

<br />
<h4>Vývoj II</h4>Zde už jen stručně heslovitě popíši další změny a úpravy. Většina dat je vyčtených z novinek ze záloh databází, ale ty nebyly pravidelné... Nejdříve byly přidány brigády (<strong class="extra">11.12.</strong>) a ankety (<strong class="extra">13.12.</strong>). Důvod jasný. Také ihned přibyly přepočty (<strong class="extra">12.12.</strong>). Hra byla totiž kvůli jednomu přepočtu pomalá a stačilo hrát 20 minut kolem jedenácté večer. Hra tím se hodně zlepšila. Obchodovalo se s palivem a nebylo to špatné. QSB hrálo docela dost lidí <span class="ultra"><em>(zhruba 50 denně)</em></span> <strong class="extra">a tak jsem rozšířil adminský tým o Hannibala</strong>. <br />
Tou dobou (leden 2007) byly na sousední hře ŽVAV zavedeny společnosti a mě napadlo, že případné stmelení hráčů do nějakých skupin napomůže komunitě i hratelnosti. Začal jsem tedy po vzoru Formule F1 pracovat na <strong class="extra">stájích</strong>. Trvalo to zhruba 3 týdny (dokončeno <strong class="extra">10.01.</strong>) a docela jsem si máknul a stáje byly opravdu děravé, takže další měsíc jsem je zdokonaloval. Během tohoto procesu jsem navrhl nový grafický design pro hru a <strong class="extra">4.3.</strong> spatřil světlo světa šedo-oranžový do dnes funkční vzhled.<br />

Další věcí, kterou se jako první rozhodl napsat Hannibal jsou banky. Podařilo se mu to během března (<strong class="extra">15.3.</strong>) a další 2 roky se to snažíme opravovat a přijít na to, jak to vlastně funguje.<br />
Během dalších týdnů hráči zjistili, že rasy jsou nevyvážené a že celý závod drobně pokulhává <span class="ultra"><em>(hlavně komenty k závodům byly špatné a chybné)</em></span>. Přepsal jsem tedy celou mechaniku závodu a zdokonalil ho. Přece jen je to to, o čem hra je. Za nějaký čas přibyl i pohár (odhaduji na <strong class="extra">duben 2007</strong>). Dalším můstkem mezi hráči a adminstvem byl help. Ten jsem se rozhodl předělat do formy dokuwiki <span class="ultra"><em>(forma wikipedie)</em></span> a stalo se tak <strong class="extra">27.4.</strong>. Dál už se blížily prázdniny a na QSB probíhali jen drobné kosmetické změny a vylazování chyb.<br />
<br />
<h4>Vývoj III</h4>Quadra Speed Boosters se dostalo i na <a href="http://festivalfantazie.cz/" class="extra">Festival fantazie</a>, kde o něm oba adminové přednášeli mnohačetnému <span class="ultra"><em>(10 +/-)</em></span> publiku. Stejně to byl úspěch. V tu dobu už byl znám nový <a href="http://help.qsb.cz/doku.php?id=koncept" class="extra">koncept</a> dílů a hodně se o něm hovořilo. Přes léto jsem si tedy vzal QSB hezky do parády a předělal kompletně systém kluzáků. Kompletní změny naleznete <a href="http://help.qsb.cz/doku.php?id=koncept_zmeny" class="extra">zde</a>. Rošíření počtu součástek v kluzáku na 10 byla obrovská novinka, která posunula vývoj QSB novým směrem. Vymyšleno bylo přes 200 předmětů <span class="ultra"><em>(hodně pomáhal Palma)</em></span> a byl opět kompletně přepsán závod <span class="ultra"><em>(za nejméně polovinu komentářových vět děkujte hráči Kyssi)</em></span>. Koncept se všemi změnami se po otestování <span class="ultra"><em>(testoval Palma, preon, StOs, Kyssi, OndraSter a Nípal)</em></span> dostal do ostrého věku <strong class="extra">7.8. 2007</strong>, ale úplně jistý si nejsem. Koncept byl poté hodněkrát upravován a doplňován, takže se nekonaly další dobu žádné větší úpravy. Neměl jsem také kvůli škole a brigádám moc času, takže pomalu mizeli hráči. Pokusil jsem se udělat pár změn, které měly vést ke zamezení bohatnutí, což byl největší problém QSB. Pořádně jsem se ke hře dostal až v květnu 2008, kdy jsem začal celou hru přepisovat <span class="ultra"><em>(jádro, takže pro hráče jen pár změn)</em></span> a po 2 měsících <span class="ultra"><em>(bylo toho hodně)</em></span> se mi to podařilo dokončit.<br />
<br />
<h4>Závěrem</h4>Závěrem bych chtěl poděkovat všem, co se na vývoji QSB podíleli, obzvlášť těm, které jsem přímo zmínil v článku. Bez některých by tato onlinovka ani nevznikla a já jsem jim za to vděčný. Na QSB se udělalo hodně práce a doufám, že to všechno bude někdy k něčemu a že do budoucna bude hra mnohem lepší :)

<br />
<br />

<div style="text-align: right">-Dr.Hadr</div>
<br />